# Generated by Django 4.1.3 on 2023-04-04 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_ticket_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_project",
                to="main.team",
            ),
        ),
    ]
